
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox4;

	private global::Gtk.FileChooserButton fileChooser;

	private global::Gtk.HBox hbox7;

	private global::Gtk.HButtonBox hbuttonbox9;

	private global::Gtk.Button btnDecrypt;

	private global::Gtk.HButtonBox hbuttonbox8;

	private global::Gtk.Label GtkLabel8;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.FileChooserButton folderChooser;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Label label4;

	private global::Gtk.Entry txtFileName;

	private global::Gtk.Label label5;

	private global::Gtk.HBox hbox6;

	private global::Gtk.HButtonBox hbuttonbox7;

	private global::Gtk.Button btnNewFile;

	private global::Gtk.HButtonBox hbuttonbox6;

	private global::Gtk.Label GtkLabel12;

	private global::Gtk.HBox hbox8;

	private global::Gtk.HButtonBox hbuttonbox11;

	private global::Gtk.Button btnEncriptar;

	private global::Gtk.HButtonBox hbuttonbox10;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment5;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label lblConn;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Label lblUser;

	private global::Gtk.Label lblPass;

	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txvConn;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Entry txtUser;

	private global::Gtk.HButtonBox hbuttonbox4;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Entry txtPass;

	private global::Gtk.HButtonBox hbuttonbox5;

	private global::Gtk.Label lblRecuadro;

	private global::Gtk.Statusbar statusBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 700;
		this.HeightRequest = 364;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Crypter");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(2));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.WidthRequest = 325;
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Seleccione un archivo"), ((global::Gtk.FileChooserAction)(0)));
		this.fileChooser.Name = "fileChooser";
		this.vbox4.Add (this.fileChooser);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fileChooser]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbuttonbox9 = new global::Gtk.HButtonBox ();
		this.hbuttonbox9.Name = "hbuttonbox9";
		this.hbox7.Add (this.hbuttonbox9);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbuttonbox9]));
		w2.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.btnDecrypt = new global::Gtk.Button ();
		this.btnDecrypt.WidthRequest = 120;
		this.btnDecrypt.Sensitive = false;
		this.btnDecrypt.CanFocus = true;
		this.btnDecrypt.Name = "btnDecrypt";
		this.btnDecrypt.UseUnderline = true;
		// Container child btnDecrypt.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Desencriptar");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.btnDecrypt.Add (w3);
		this.hbox7.Add (this.btnDecrypt);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnDecrypt]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbuttonbox8 = new global::Gtk.HButtonBox ();
		this.hbuttonbox8.Name = "hbuttonbox8";
		this.hbox7.Add (this.hbuttonbox8);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbuttonbox8]));
		w12.Position = 2;
		this.vbox4.Add (this.hbox7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox7]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.frame2.Add (this.GtkAlignment);
		this.GtkLabel8 = new global::Gtk.Label ();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Archivo existente:</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel8;
		this.hbox5.Add (this.frame2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame2]));
		w16.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.folderChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Seleccione una carpeta"), ((global::Gtk.FileChooserAction)(2)));
		this.folderChooser.Name = "folderChooser";
		this.vbox5.Add (this.folderChooser);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.folderChooser]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre del archivo:");
		this.hbox9.Add (this.label4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label4]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.txtFileName = new global::Gtk.Entry ();
		this.txtFileName.CanFocus = true;
		this.txtFileName.Name = "txtFileName";
		this.txtFileName.IsEditable = true;
		this.txtFileName.InvisibleChar = '●';
		this.hbox9.Add (this.txtFileName);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.txtFileName]));
		w19.Position = 1;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0f;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString (".conf");
		this.hbox9.Add (this.label5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label5]));
		w20.Position = 2;
		w20.Fill = false;
		this.vbox5.Add (this.hbox9);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbuttonbox7 = new global::Gtk.HButtonBox ();
		this.hbuttonbox7.Name = "hbuttonbox7";
		this.hbox6.Add (this.hbuttonbox7);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbuttonbox7]));
		w22.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnNewFile = new global::Gtk.Button ();
		this.btnNewFile.WidthRequest = 120;
		this.btnNewFile.Sensitive = false;
		this.btnNewFile.CanFocus = true;
		this.btnNewFile.Name = "btnNewFile";
		this.btnNewFile.UseUnderline = true;
		// Container child btnNewFile.Gtk.Container+ContainerChild
		global::Gtk.Alignment w23 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w24 = new global::Gtk.HBox ();
		w24.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w25 = new global::Gtk.Image ();
		w25.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
		w24.Add (w25);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w27 = new global::Gtk.Label ();
		w27.LabelProp = global::Mono.Unix.Catalog.GetString ("Nuevo");
		w27.UseUnderline = true;
		w24.Add (w27);
		w23.Add (w24);
		this.btnNewFile.Add (w23);
		this.hbox6.Add (this.btnNewFile);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnNewFile]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbuttonbox6 = new global::Gtk.HButtonBox ();
		this.hbuttonbox6.Name = "hbuttonbox6";
		this.hbox6.Add (this.hbuttonbox6);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbuttonbox6]));
		w32.Position = 2;
		this.vbox5.Add (this.hbox6);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		this.GtkAlignment2.Add (this.vbox5);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel12 = new global::Gtk.Label ();
		this.GtkLabel12.Name = "GtkLabel12";
		this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Nuevo archivo:</b>");
		this.GtkLabel12.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel12;
		this.hbox5.Add (this.frame3);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame3]));
		w36.Position = 1;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		w37.Padding = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbuttonbox11 = new global::Gtk.HButtonBox ();
		this.hbuttonbox11.Name = "hbuttonbox11";
		this.hbox8.Add (this.hbuttonbox11);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbuttonbox11]));
		w38.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.btnEncriptar = new global::Gtk.Button ();
		this.btnEncriptar.WidthRequest = 150;
		this.btnEncriptar.Sensitive = false;
		this.btnEncriptar.CanFocus = true;
		this.btnEncriptar.Name = "btnEncriptar";
		this.btnEncriptar.UseUnderline = true;
		// Container child btnEncriptar.Gtk.Container+ContainerChild
		global::Gtk.Alignment w39 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w40 = new global::Gtk.HBox ();
		w40.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w41 = new global::Gtk.Image ();
		w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-descending", global::Gtk.IconSize.Menu);
		w40.Add (w41);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w43 = new global::Gtk.Label ();
		w43.LabelProp = global::Mono.Unix.Catalog.GetString ("Encriptar");
		w43.UseUnderline = true;
		w40.Add (w43);
		w39.Add (w40);
		this.btnEncriptar.Add (w39);
		this.hbox8.Add (this.btnEncriptar);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnEncriptar]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbuttonbox10 = new global::Gtk.HButtonBox ();
		this.hbuttonbox10.Name = "hbuttonbox10";
		this.hbox8.Add (this.hbuttonbox10);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbuttonbox10]));
		w48.Position = 2;
		this.vbox1.Add (this.hbox8);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		this.GtkAlignment5.BorderWidth = ((uint)(6));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblConn = new global::Gtk.Label ();
		this.lblConn.Name = "lblConn";
		this.lblConn.Xalign = 1f;
		this.lblConn.LabelProp = global::Mono.Unix.Catalog.GetString ("Cadena de conexión:");
		this.vbox3.Add (this.lblConn);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lblConn]));
		w50.Position = 0;
		w50.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.BorderWidth = ((uint)(18));
		this.vbox3.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbuttonbox1]));
		w51.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblUser = new global::Gtk.Label ();
		this.lblUser.Name = "lblUser";
		this.lblUser.Xalign = 1f;
		this.lblUser.LabelProp = global::Mono.Unix.Catalog.GetString ("Súper Usuario:");
		this.vbox3.Add (this.lblUser);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lblUser]));
		w52.Position = 2;
		w52.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblPass = new global::Gtk.Label ();
		this.lblPass.Name = "lblPass";
		this.lblPass.Xalign = 1f;
		this.lblPass.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña:");
		this.vbox3.Add (this.lblPass);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lblPass]));
		w53.Position = 3;
		w53.Fill = false;
		this.hbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txvConn = new global::Gtk.TextView ();
		this.txvConn.Sensitive = false;
		this.txvConn.CanFocus = true;
		this.txvConn.Name = "txvConn";
		this.txvConn.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.txvConn);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w56.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtUser = new global::Gtk.Entry ();
		this.txtUser.Sensitive = false;
		this.txtUser.CanFocus = true;
		this.txtUser.Name = "txtUser";
		this.txtUser.IsEditable = true;
		this.txtUser.WidthChars = 36;
		this.txtUser.InvisibleChar = '●';
		this.hbox3.Add (this.txtUser);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtUser]));
		w57.Position = 0;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		this.hbox3.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbuttonbox4]));
		w58.Position = 1;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w59.Position = 1;
		w59.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtPass = new global::Gtk.Entry ();
		this.txtPass.Sensitive = false;
		this.txtPass.CanFocus = true;
		this.txtPass.Name = "txtPass";
		this.txtPass.IsEditable = true;
		this.txtPass.WidthChars = 36;
		this.txtPass.InvisibleChar = '●';
		this.hbox4.Add (this.txtPass);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtPass]));
		w60.Position = 0;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		this.hbuttonbox5.BorderWidth = ((uint)(12));
		this.hbox4.Add (this.hbuttonbox5);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbuttonbox5]));
		w61.Position = 1;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w62.Position = 2;
		w62.Expand = false;
		w62.Fill = false;
		this.hbox2.Add (this.vbox2);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
		w63.Position = 1;
		this.GtkAlignment5.Add (this.hbox2);
		this.frame1.Add (this.GtkAlignment5);
		this.lblRecuadro = new global::Gtk.Label ();
		this.lblRecuadro.Name = "lblRecuadro";
		this.lblRecuadro.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Datos del archivo: </b>");
		this.lblRecuadro.UseMarkup = true;
		this.frame1.LabelWidget = this.lblRecuadro;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
		w66.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusBar = new global::Gtk.Statusbar ();
		this.statusBar.Name = "statusBar";
		this.statusBar.Spacing = 6;
		this.vbox1.Add (this.statusBar);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusBar]));
		w67.Position = 3;
		w67.Expand = false;
		w67.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 708;
		this.DefaultHeight = 411;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fileChooser.SelectionChanged += new global::System.EventHandler (this.OnFileChooserSelectionChanged);
		this.btnDecrypt.Clicked += new global::System.EventHandler (this.OnBtnDecryptClicked);
		this.txtFileName.TextInserted += new global::Gtk.TextInsertedHandler (this.OnTxtFileNameTextInserted);
		this.btnNewFile.Clicked += new global::System.EventHandler (this.OnBtnNewFileClicked);
		this.btnEncriptar.Clicked += new global::System.EventHandler (this.OnBtnEncriptarClicked);
	}
}
